#!/bin/bash

OUT_DIR=build

echo "Building engine $1"

rm -rf ${OUT_DIR}
mkdir -p ${OUT_DIR}

# Primary esbuild for chess engine and worker scripts.
yarn esbuild \
  src/script/perft.ts \
  src/script/engine.ts \
  src/chess/workers/timer.ts \
  src/chess/workers/search-executor.ts \
  --bundle \
  --platform=node \
  --format=esm \
  --minify \
  --define:USE_NODE_WORKER_THREAD=true \
  --out-extension:.js=.mjs \
  --entry-names=[name] \
  --outdir=${OUT_DIR}
  # --analyze

# Make built scripts easily executable
for executableName in engine.mjs perft.mjs; do
  chmod u+x ${OUT_DIR}/${executableName}
  sed -i '.bak' '1s/^/#!\/usr\/bin\/env node\'$'\n/g' ${OUT_DIR}/${executableName}
  rm ${OUT_DIR}/${executableName}.bak
done

# Move the built engine to a named directory.
if [ -z "$1" ]; then
  echo "No name for engine version to build, exiting without copy"
else
  rm -rf vendor/engine-builds/$1
  cp -r $OUT_DIR vendor/engine-builds/$1
fi

# Build the chess web app
# vite build
