#!/bin/bash

OUT_DIR=build

rm -rf ${OUT_DIR}
mkdir -p ${OUT_DIR}

yarn esbuild \
  src/script/perft.ts \
  src/script/engine.ts \
  src/chess/workers/worker-thread/timer.ts \
  src/chess/workers/worker-thread/search-executor.ts \
  --bundle \
  --platform=node \
  --format=esm \
  --minify \
  --define:USE_NODE_WORKER_THREAD=true \
  --out-extension:.js=.mjs \
  --entry-names=[name] \
  --outdir=${OUT_DIR} "$@"
  # --analyze

# Build the chess web app
# vite build
